#服务器端口
server:
  port: 8106

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        allow : 127.0.0.1
        deny : 192.168.0.0
        url-pattern: /druid/*

swagger:
  title: bid-admin 接口文档系统
  description: bid-admin 接口文档系统
  version: 2.4.0
  base-packages: cn.teleinfo.bidadmin
  contact:
    name: shiweijun
    email: shiweijun@teleinfo.cn