#服务器端口
server:
  port: 8203

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
swagger:
  title: bid-admin 接口文档系统
  description: bid-admin 接口文档系统
  version: 2.4.0
  base-packages: cn.teleinfo.bidadmin
  contact:
    name: shiweijun
    email: shiweijun@teleinfo.cn