#服务器端口
server:
  port: 8102

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  data:
    elasticsearch:
      cluster-name: bidadmin
      cluster-nodes: 172.17.3.40:9300,172.17.3.41:9300,172.17.3.42:9300
  elasticsearch:
    rest:
      uris: ["http://172.17.3.40:9200","http://172.17.3.41:9200","http://172.17.3.42:9200"]
bif:
  loadMsgPrivate: d37df84af4156fe9ab65a5642418cd7bd9e9371acb5ae1bd282d1d473bcb1f13
  urls: http://36.112.25.14:5320
  chainId: 444
  superNode : 2

identity:
  certificate:
    # Context
    context: https://example.com/realname/template/v1
    # 身份信任锚拥有者地址
    owner: did:bid:6cc796b8d6e2fbebc9b3cf9e
    # 身份信任锚拥有者私钥
    privateKey: d37df84af4156fe9ab65a5642418cd7bd9e9371acb5ae1bd282d1d473bcb1f13
    # 私钥类型
    keyType: ECDSAwithSHA256
    # 有效期
    period: 2
    # format
    format: pgp

ipfs:
  multiAddr: /ip4/39.99.132.122/tcp/5001
  host: 39.99.132.122
  uploadPort: 5001
  catPort: 8080

swagger:
  title: bid-admin 接口文档系统
  description: bid-admin 接口文档系统
  version: 2.4.0
  base-packages: cn.teleinfo.bidadmin
  contact:
    name: shiweijun
    email: shiweijun@teleinfo.cn